# Generated by Django 5.0.6 on 2024-05-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_user_options_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
