# Generated by Django 5.0.6 on 2024-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_book_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/cover.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
