# Generated by Django 5.0.6 on 2024-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='cover.jpg', upload_to=''),
        ),
    ]
