# Generated by Django 5.0.6 on 2024-05-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
