# Generated by Django 5.0.6 on 2024-05-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Book_Reservation',
            },
        ),
    ]
