# Generated by Django 5.0.6 on 2024-05-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_bookreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='book',
            field=models.ForeignKey(default=7, editable=False, on_delete=django.db.models.deletion.CASCADE, to='manager.book'),
            preserve_default=False,
        ),
    ]
