# Generated by Django 5.0.6 on 2024-05-26 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_bookreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='reserve_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
