# Generated by Django 5.0.6 on 2024-05-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_bookreservation_reserve_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('On Loan', 'On Loan')], default='reserved', max_length=50),
            preserve_default=False,
        ),
    ]
