# Generated by Django 5.0.6 on 2024-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_bookreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='bookreservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('On Loan', 'On Loan'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Late', 'Late')], max_length=50),
        ),
    ]
